/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_CHAINABLELED_H
#define _JERRYSCRIPT_MBED_CHAINABLELED_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

DECLARE_CLASS_CONSTRUCTOR(ChainableLED);

#endif // _JERRYSCRIPT_MBED_CHAINABLELED_H
